# Generated by Django 5.2.5 on 2025-08-23 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0002_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
