# Generated by Django 5.2.5 on 2025-08-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0003_customuser_supervisor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
    ]
