# Generated by Django 5.2.5 on 2025-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0004_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title for supervisors (e.g., Dr, Prof, Mr, Mrs)",
                max_length=20,
                null=True,
            ),
        ),
    ]
