# Generated by Django 5.2.5 on 2025-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0005_customuser_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="remark",
            field=models.TextField(
                blank=True,
                help_text="Supervisor remark or comment for this submission",
                null=True,
            ),
        ),
    ]
