# Generated by Django 5.2.5 on 2025-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0006_submission_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
