# Generated by Django 5.2.5 on 2025-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0007_alter_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="overview",
            field=models.CharField(
                blank=True,
                help_text="Short summary of what you did today",
                max_length=255,
                null=True,
            ),
        ),
    ]
