# Generated by Django 5.2.5 on 2025-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0008_submission_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lecturer_id",
            field=models.CharField(
                blank=True,
                help_text="Lecturer ID for supervisors",
                max_length=20,
                null=True,
            ),
        ),
    ]
