# Generated by Django 5.2.5 on 2025-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SIWES", "0009_customuser_lecturer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True, help_text="Department name", max_length=100, null=True
            ),
        ),
    ]
